name: bitti
description: "1-bit journal."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  cloud_firestore: ^5.6.1
  firebase_core: ^3.10.0
  flex_color_picker: ^3.7.0
  get_it: ^8.0.3
  either_dart: ^1.0.0
  localstorage: ^5.0.0
  go_router: ^14.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.2
  build_runner: ^2.4.14

flutter:
  uses-material-design: true